# Site settings
title: Serguei Cambour
twitter_username: belgoros
name: Serguei Cambour

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
  - title: GitHub
    url: https://github.com/belgoros
  - title: StackOverflow
    url: http://stackoverflow.com/users/1119043/belgoros
  - title: DZone
    url: https://dzone.com/users/224218/jcrusoe.html
  - title: LinkedIn
    url: https://be.linkedin.com/in/sergueicambour

#Any buzzword skills you want to include
skills:
  - Ruby
  - Ruby on Rails
  - Elixir
  - Phoenix
	- Ecto
  - JRuby
  - Cucumber
  - RSpec
  - Capybara
  - Tailwind CSS
  - Java EE
  - Spring MVC
  - Spring Boot
  - JPA/Hibernate
  - Tapestry
  - GraphQL/Absinthe
  - Maven
  - Ember JS
  - Docker
  - Kubernetes
  - Git/GitLab/GitHub/Bitbucket

#Work experience is required
roles:
  - title: Senior Consultant/Engineer
    start: February 2021
    end: ongoing
    employer: Capgemini Engineering, Brussels, Belgium
    description: I'm involved in different projects and primarily working on client sites in Communications, Financial, Retail and Transport Services.

  - title: Senior Software Engineer
    start: February 2020
    end: February 2021
    employer: Devoteam, Brussels, Belgium
    description: I'm involved in different projects and primarily working on client sites in Communications, Financial, Retail and Transport Services.
  - title: Senior Software Engineer
    start: January 2014
    end: January 2020
    employer: INETUM (former GFI Informatique), Lille, France
    description: I'm involved in different projects and primarily working on client sites in Communications, Financial, Retail and Transport Services.
  - title: Ruby on Rails Engineer
    start: Oct.2013
    end: Feb. 2014
    employer: Teleborder, USA
    description: Migration to Rails 4, fix compatibilities issues
  - title: Ruby on Rails Engineer
    start: Oct.2013
    end: Jan.2014
    employer: Silicon Salad, Lille, France
    description: WEB agency specialized in e-commerce solutions.</br>I'm involved in evaluating and support of existing Rails applications.
  - title: Software Engineer
    start: June 2010
    end: June 2013
    employer: Atos Integration, France
    description: A range of technical roles, primarily working on client sites in Financial, Retail, Transport Services.
  - title: Software Engineer
    start: March 2007
    end: March 2010
    employer: Aubay.Promotic, Belgium
    description: A range of technical roles, primarily working on client sites in Retail, Transport Services, Public and State Institutions.

#Education is required
education:
  - level: Master of Engineering
    date: 1991
    subject: Computer Sciences and Information Technology
    school: Kuban State University, Krasnodar, Russia

#This section is optional (as is the image link below)
courses:
  - title: Full-Stack Phoenix (The Pragmatic Studio)
    link: https://pragmaticstudio.com/phoenix
    date: November 2024 - March 2025
  - title: Learn Phoenix LiveView (Arrowsmithlabs)
    link: https://arrowsmithlabs.com
    date: August 2024-September 2024
  - title: The Ultimate Elixir Course (Learn-Elixir.dev)
    link: https://learn-elixir.dev
    date: December 2023-June 2024
  - title: Associate Cloud Engineer, GCP
    link: https://cloud.google.com/learn/certification/cloud-engineer
    date: January-February 2024
  - title: Elixir Engineer, DockYard Academy
    link: https://github.com/DockYard-Academy
    date: July 2023
  - title: Build an MVP With Elixir
    link: https://pjullrich.gumroad.com/l/bmvp
    date: June 2023
  - title: The Complete Elixir and Phoenix Bootcamp, Udemy
    link: https://www.udemy.com/course/the-complete-elixir-and-phoenix-bootcamp-and-tutorial/
    date: April - May 2021
  - title: Kubernetes Certified Application Developer (CKAD), Udemy
    link: https://www.udemy.com/course/certified-kubernetes-application-developer/
    date: Feb - March 2021
  - title: Coding Elixir, The Coding Gnome
    link: https://codestool.coding-gnome.com/courses/elixir-for-programmers-2
    date: April - May 2019
  - title: shaping-up-with-angular-js
    link: https://www.codeschool.com/courses/shaping-up-with-angular-js
    date: September 2014
  - title: Front End Formations
    link: https://www.codeschool.com/courses/front-end-formations
    date: June, 2014
  - title: JavaScript Best Practices
    link: https://www.codeschool.com/courses/javascript-best-practices
    date: June, 2014
  - title: Surviving APIs with Rails
    link: https://www.codeschool.com/courses/surviving-apis-with-rails
    date: June, 2014
  - title: Rails 4 Patterns
    link: https://www.codeschool.com/courses/rails-4-patterns
    date: June, 2014
  - title: Testing with RSpec
    link: https://www.codeschool.com/courses/testing-with-rspec
    date: June, 2014
  - title: Rails Testing for Zombies
    link: https://www.codeschool.com/courses/rails-testing-for-zombies
    date: June, 2014
  - title: Rails for Zombies 2
    link: https://www.codeschool.com/courses/rails-for-zombies-2
    date: May, 2014
  - title: Rails for Zombies Redux
    link: https://www.codeschool.com/courses/rails-for-zombies-redux
    date: May, 2014
  - title: Ruby Bits Part 2
    link: https://www.codeschool.com/courses/ruby-bits-part-2
    date: May, 2014
  - title: Rails 4:Zombie Outlaws
    link: https://www.codeschool.com/courses/rails-4-zombie-outlaws
    date: May, 2014
  - title: Git Real
    link: https://www.codeschool.com/courses/git-real
    date: May, 2014
  - title: Git Real 2
    link: https://www.codeschool.com/courses/git-real-2
    date: May, 2014
  - title: Mastering GitHub
    link: https://www.codeschool.com/courses/mastering-github
    date: May, 2014
  - title: Try Git
    link: https://www.codeschool.com/courses/try-git
    date: May, 2014

apps:
  - name: Decastore API
    url: https://github.com/belgoros/decastore-api
    description: Decathlon back-office API
  - name: Slax
    url: https://github.com/belgoros/slax
    description: Phoenix app, clone of Slack application
  - name: UMed
    url: https://github.com/belgoros/umed
    description: Quiz for students in medicine (Rails)
  - name: Heads Up
    url: https://github.com/belgoros/heads_up
    description: Phoenix Web application

#List of interesting Github repo/projects to include - optional
github:
  - belgoros/slax
	- belgoros/heads_up
	- belgoros/calendlex
	- belgoros/budgie
  - belgoros/decastore-api
  - belgoros/decastore-front
  - belgoros/spot-time

#Stackoverflow flair is optional
stackoverflow:
  profileurl: https://stackoverflow.com/users/1119043/belgoros
  flairimageurl: https://stackoverflow.com/users/flair/1119043.png

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring, JPA (Hibernate) in addition to others.<br/><br/>
  <strong>Web Development</strong>: My server side web development experience has largely been based on the Ruby on Rails and Spring MVC frameworks. But I'm doing my best to learn more Elixir and Phoenix. I have also worked with some client side technology, having used Ember JS, Tailwind CSS, Bootstrap, Foundation, LESS, SASS and have also experimented with other technologies such as Angular, Backbone, CoffeeScript.<br/><br/>
  <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with GitLab, GitHub, Bitbucket, CVS, SVN, Maven, Sonar, Jira and Jenkins. I have experience with lots of testing tools and technologies.<br/><br/>
  I have also gained experience and knowledge from several side projects and research that I have undertaken in my free time, including Amazon S3, PayPal.<br/><br/>
  I created, and am now primary contributor to a Rails quiz application for students in medicine: <a target='_blank' href="https://github.com/belgoros/umed">UMed</a>, which provides integration with PayPal API and Amazon S3. <br/><br/>
